version: "2.2"
services:
  achat-db:
    image: mysql:8
    container_name: achat-mysql
    restart: always
    environment:
      MYSQL_DATABASE: achat
      MYSQL_ROOT_PASSWORD: 9ar9ouch
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql/achat-data:/var/lib/mysql
    networks:
      - devops

  achat:
    build: ./
    restart: always
    environment:
      - spring.datasource.url=jdbc:mysql://achat-db:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=9ar9ouch
    ports:
      - "8089:8089"
    depends_on:
      - achat-db
    networks:
      - devops

volumes:
  achatdb:

networks:
  devops:
    external: true